apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: adjablou
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - name: app-service
      port: 5000
      targetPort: 5000
