apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: adjablou
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: docker pull harbor.dev.afsmtddso.com/adjablou/app@sha256:bde8d9398dc7652c3d6ab92f7a8585105699dbdd60b7b81d076fda7502b85478
        ports:
        - containerPort: 5000
